config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  resources :items do
  	member do
  		patch :complete
  		patch :reverse
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	def completed?
		!completed_at.blank?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all.order("created_at DESC")
	end


	def new
		@item = Item.new
	end


	def create
		@item = Item.new(item_params)

		if @item.save
			redirect_to items_path
		else
			render "new"
		end

	end


	def show
		@item = Item.find(params[:id])
	end


	def edit
		@item = Item.find(params[:id])
	end


	def update 
		@item = Item.find(params[:id])

		if @item.update(item_params)
			redirect_to root_path
		else
			render 'edit'
		end

	end

	def destroy
		@item = Item.find(params[:id])

		@item.destroy
		redirect_to root_path
	end

	def complete
		@item = Item.find(params[:id])
		@item.update_attribute(:completed_at, Time.now)
		redirect_to root_path
	end

	def reverse
		@item = Item.find(params[:id])
		@item.update_attribute(:completed_at, nil)
		redirect_to root_path
	end


	private def item_params
		params.require(:item).permit(:title, :description)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
%h2 Bearbeite den Post #{@item.id}

= form_for @item do |f|
	%p
		= f.label :title
		%br
		= f.text_field :title
		%br
	%p
		= f.label :description
		%br
		= f.text_area :description
		%br
	%p
		= f.submit "Bearbeiten"

app/views/items/index.html.haml
%h1{:class => "heading"}Deine To-Do's
%hr

.button-wrapper.text-center
	%button{:type => "button", :class =>"btn btn-default btn-main"}
		= link_to "Neuer Task", new_item_path

.content-wrapper
	- @items.each do |item|
		.row
			- if item.completed?
				.col-md-6
					%s
						%h2= link_to item.title, item
					%figure= "Erledigt vor: #{time_ago_in_words(item.completed_at)}"
				.col-md-2 
					=link_to reverse_item_path(item), method: :patch do
						%p{:class=>"text-success"} Done
			- else
				.col-md-6
					%h2= link_to item.title, item
					%p= item.description
				.col-md-2 
					= link_to complete_item_path(item), method: :patch do 
						%p{:class=>"text-danger"} Check

app/views/items/new.html.haml
%h1 Hier kann ein neuer Task angelegt werden.
= form_for @item do |f|
	%p
		= f.label :title
		%br
		= f.text_field :title
		%br
	%p
		= f.label :description
		%br
		= f.text_area :description
		%br
	%p
		= f.submit "Posten"

app/views/items/show.html.haml
%h2= @item.title
%p= @item.description

-if @item.completed?
	%p{:style => "color:red"} Erledigt

=link_to "Zurück", root_path
=link_to "Bearbeiten", edit_item_path
=link_to "Löschen", item_path(@item), method: :delete, data:{ confirm: "Sicher?"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Myapp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  .container
    = yield